### PR TITLE
Fixes to work with Run 2 MC.

### PR DESCRIPTION
**Pull request by matz-e**
Most notably, the name of the b-tag discriminant changed!  @puigh should this be implemented with a switch?

### CODE REVIEW

**Comment by puigh** [comment]
Is this the only change that is necessary to work with Run 2 MC? My concern is that we don't want to have too many of these switches. My personal opinion is that there should be one global thing we switch to change between one campaign and the other, or I think that we should have a specific branch or tag to have the code work for a given campaign. What do you think?

**Comment by matz-e** [comment]
The changes from `float` to `double` were the only compilation errors I got, and the b-tagging discriminant is the only other change I've run across so far.  But I have not yet produced any valid ntuples / investigated them closely, so there may be more lurking in there.

As far as managing this, I personally would prefer to have a tag/branch for Phys14.  This would keep the code simpler, and I don't expect to look at Phys14 that much any more in the future.  Very important changes could be back-ported by cherry-picking commits.  13 TeV vs future 14 TeV should probably be managed similar to `BEANHelper`, though (but maybe with one single option, with a default, instead of 20 arguments to the constructor of the helper.)

**Comment by puigh** [comment]
I agree, and I would support having a tag/branch for Phys14. I also agree
that a change between campaigns should be done with a single option unless
there is some reason why it absolutely cannot. Including more than a
handful of arguments to a constructor is bound to cause more confusion.

**Comment by matz-e** [comment]
With the call to switch over to Run II MC, should I create a `phys14` branch and merge this?

**Comment by puigh** [comment]
Yes, I think having a phys14 branch is the way to go. We're going to want
to have this for all the groups looking at RunII MC.

Can you also update the markdown file with some short details? Some people
may not know we are switching to using branches.

**Comment by matz-e** [comment]
Robin already has taken care of this.

**Pull request closed without merging**
