### PR TITLE
change file path in function jetdPtMatched()

### PR DESCRIPTION
**Pull request by abhisek92datta**
to make it more general

### CODE REVIEW

**Comment by michaelwassmer** [comment]
I think you are still on an older version, because there was already a pull request, which was merged and generalized the path aswell as some changes to the function jetdPtMatched

**Comment by abhisek92datta** [comment]
okay.. so which branch is the latest that I should use ?

**Comment by michaelwassmer** [comment]
CMSSW_8_0_8 should have it.

**Comment by abhisek92datta** [comment]
Thanks

**Pull request closed without merging**
