### PR TITLE
Cmssw 8 0 8 gen jet matching

### PR DESCRIPTION
**Pull request by hsatoshi**
This modification is for reco-gen jet matching.

So far, we have used gen-jet which is already associated with a reco-jet, while the matching can fail in case there are more than one candidate in the cone.
We need, however, to tryall the combination of reco-gen jet (within certain distance)
 to see if there are any good combination.

The modification changes the interface of 
 GetCorrectedJet() and the counterpart of AK8 
 so that it takes also Genjet information.

### CODE REVIEW

**Comment by hsatoshi** [comment]
Need clarification : 

Do we require dr(reco,gen) < 0.2, which is a half of radius of AK4, to also AK8 jet instead of 0.4 ?
https://github.com/cms-ttH/MiniAOD/pull/28/files#diff-3953df125a12b699bb390a281ecf8c0eR2434

**Comment by abhisek92datta** [comment]
Yes it was my mistake. I think it should be half of radius i.e 0.4 for AK8. If I change it now in my branch, will the pull request reflect that change ?

**Comment by hsatoshi** [comment]
I confirm.
I think we can merge this modification.

If no objection, let us merge this 5pm(cern) today.

**Comment by hsatoshi** [comment]
I merged the RP.
Thank you so much, Abhisek, for this work.

**Comment by abhisek92datta** [comment]
No Problem.

**Pull request merged**
